/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as storage from "./storage";
export type { storage };
import type * as testSol from "./test.sol";
export type { testSol };
export type { SocialRecoveryModule } from "./SocialRecoveryModule";
