/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as storage from "./storage";
export type { storage };
export type { SocialRecoveryModule } from "./SocialRecoveryModule";
