/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GuardianStorage } from "./GuardianStorage";
export type { IGuardianStorage } from "./IGuardianStorage";
