/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as storage from "./storage";
export * as testSol from "./test.sol";
export { SocialRecoveryModule__factory } from "./SocialRecoveryModule__factory";
