/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GuardianStorage__factory } from "./GuardianStorage__factory";
export { IGuardianStorage__factory } from "./IGuardianStorage__factory";
