/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MyNFT__factory } from "./MyNFT__factory";
export { SampleNFT__factory } from "./SampleNFT__factory";
